### ISSUE TITLE
Live changing background colour isn't working

### ISSUE THREAD

**Issue by hianzing** [CybrHome/custom-background.js#4]
Hello, good afternoon. I have downloaded and "installed" the folder: custombg into my webpage directory. I am using this feature in my php & html code, running on USBWebserver v8.6. However, the live changing background colour just doesn't work locally. The rest is working perfectly fine. Thanks in advance!

**Comment by ShubhamBadal** [comment]
Congratulations on opening your first issue on GitHub! 

I hope you've seen the demo and as you can see Colors Auto-Change mode is working properly in the demo page I've hosted. So you can try these two things and let us know here.

1. Please check if you're seeing any errors in console in your pages when you're running custom-background.js locally. 

2. Simply download the repo and run the demo site we've made locally without altering anything or integrating in your site. You'll find demo page in 'docs' folder. Check if at-least that's working on your browser locally.

**Comment by hianzing** [comment]
Thanks for the warm welcome!

Yes, the online demo page is working just fine. The demo page in 'docs' folder does not work for your information.

1. I had fixed 404 error regarding unable to call jquery-ui but still there's no improvements including clearing the cache.

2. I found that  `<script type="text/javascript" src="custombg/js/custombg-loader.js"></script>` was placed wrongly in my code so i fixed it, but no improvements as well.

3. Pictures of demo and index not working 
![demo](https://user-images.githubusercontent.com/42140414/43723595-97d04b94-99ca-11e8-9f52-c58d9d413e00.JPG)
![index](https://user-images.githubusercontent.com/42140414/43723603-9d22f72c-99ca-11e8-86a3-2a4c95d46a9c.JPG)

4. There's no style when 'saved' button is clicked from my locally hosted webpage.
![no style](https://user-images.githubusercontent.com/42140414/43723678-d0eb89fc-99ca-11e8-8008-7da80fed302a.JPG)
(left is yours, right is mine)

4. In fact, i think the problem is that the background color of style is wrongly coded (?):
**My code (from your zip file)**
![in fact](https://user-images.githubusercontent.com/42140414/43723636-b0728752-99ca-11e8-876f-b44049820727.JPG)

**Your online host code**
![yours style](https://user-images.githubusercontent.com/42140414/43723741-ee3ce14a-99ca-11e8-8858-3c037a3fa870.JPG)

Thanks again!

**Comment by ShubhamBadal** [comment]
demo.html in docs folder works fine, just tested it on my mac after your reply.

Have you checked errors in console? Please check and if there are any errors there send screenshots.

Note: Also if you're trying to run these html pages without any properly working web server, then it won't work and will cause a similar issue. Do not run by the demo just opening its html files in browser. 

Configure apache, nginx, IIS or any web server and use the web server (on localhost or 127.0.0.1) to run the docs folder's html files. It should work that way. I just tried docs folder on my localhost web server and it worked fine.

**Comment by hianzing** [comment]
**Demo worked. But my other webpage isnt working**

Nope there's no error regarding the jquery-ui. The error does not affect as I had temporarily disabled the script that caused the error but still no improvements.
![no eror](https://user-images.githubusercontent.com/42140414/43727370-5572fde6-99d4-11e8-8a79-3c027b824756.JPG)

Edit: I created a new php file based on your demo.html and it worked. Perhaps there are conflicts in my old php webpage file, but im not sure where tho

Edit 2: Got it solved! Apparently I forgot that I had another javascript jquery3.1 script that is linked to my main php code. But aren't they the same thing? Why does it causes conflict though

**Comment by ShubhamBadal** [comment]
Good! On any web page you can/should call jQuery library only once (and its the same case will most other libraries too) otherwise usually you'll get errors and issue no matter which project you're working on.

**Comment by hianzing** [comment]
Oh I see..thanks for the advice all these while!
