### ISSUE TITLE
'Save' button don't work for some pictures

### ISSUE THREAD

**Issue by hianzing** [CybrHome/custom-background.js#5]
When I click on 'save' button, for **Choose Image** section, it doesn't work for some pictures. For example, on the live demo page, saving the Harry Potter picture doesn't work. Locally on my pc, all the pictures somehow don't work except for one. 

Errors shows that `GET http://localhost:8080/voon/null 404 (Not Found)` when I wanted to save the Harry Potter image locally & also for other pictures of mine. 

Is it because there is certain restrictions towards pictures that are being used?

**Comment by hianzing** [comment]
Error occurred during live demo: 
![error](https://user-images.githubusercontent.com/42140414/43849820-e6811cd8-9b68-11e8-95bf-6993f9e99e74.JPG)

**Comment by ShubhamBadal** [comment]
Again if the online demo is working properly with your picture uploads from your PC, then there is a problem with how you have configured your local project (PHP, apache, file permissions, etc.).

Please check if everything is fine with the online demo.

**Comment by hianzing** [comment]
It worked when pictures are smaller than 500kb..hmm kinda weird
